### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by yukiyakiZ** [THUNLP-MT/L2Copy4APE#1]
Hi, 
It is said in your paper that the code is available here...
I wondered when it will be updated.
Thanks in advance.

**Comment by xc-kiwiberry** [comment]
Our paper are not public aviable now.
We will release our code before November.
Thanks for your attention.

**Comment by xc-kiwiberry** [comment]
Our paper is not public available now.
We will release our code before November.
Thanks for your attention.
