### ISSUE TITLE
Is it OK to not use joint vocabulary?

### ISSUE THREAD

**Issue by HuihuiChyan** [THUNLP-MT/L2Copy4APE#2]
Dear auther, your work is excellent. But I want to use your code on Chinese-English APE, so I think joint vocabulary is not a good idea.
If I choose not to use joint vocabulary, where should I put my three vocabulary file?
In your demo bash file is like this:
    --vocabulary ${vocab_joint} ${vocab_joint}
with only two positions, while I have three vocabularies for src, mt and pe.

**Comment by xc-kiwiberry** [comment]
Sorry, my code assumes that the vocabulary is shared by three sides, you may need to edit thumt/models/transformer.py to meet your needs. :）
