### ISSUE TITLE
BPE code file

### ISSUE THREAD

**Issue by jlin816** [THUNLP-MT/L2Copy4APE#4]
To run the pretrained model in your repo, I think we would need the BPE code file (to run apply_bpe.py and preprocess the input at inference time). It looks like you've only included the vocab.txt in the Google Drive checkpoint. Are you able to provide the `bpe32k` file as well?

**Comment by xc-kiwiberry** [comment]
Thanks for your attention. I uploaded `bpe32k` just now. :)
